### ISSUE TITLE
Actually there's few usable text now for this dataset

### ISSUE THREAD

**Issue by HeroadZ** [tatHi/tweet_extructor#1]
Is there any usable japanese twitter sentiment dataset recommended?

**Comment by tatHi** [comment]
Unfortunately, there is no available dataset including Japanese sentiment analysis on twitter other than the [dataset](http://www.db.info.gifu-u.ac.jp/data/Data_5d832973308d57446583ed9f) mentioned in README.md, as far as I know.
Thanks.

**Comment by tatHi** [comment]
If you don't stick to Twitter dataset, I recommend [Rakuten dataset](https://rit.rakuten.co.jp/data_release/).
The dataset includes customer's reviews for products, and you can use it for rating prediction from each review.
From your profile, you look a student in Japan, so I guess you can get the dataset easily via the professor of your lab.

**Comment by HeroadZ** [comment]
Thank you for you advices. But maybe I cannot access it because the research I'm doing now is from a company where I work as an intern. 😢
